IndoorOperatorStation/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import re_path

urlpatterns = [
    re_path('admin/', admin.site.urls),
    re_path(r'^', include('agent.urls')),
]

agent/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views


app_name = 'agent'

urlpatterns = [
    path('api/', views.API.as_view()),
    path('api/takeoff/', views.Takeoff.as_view(), name='takeoff'),
    path('api/direction/', views.SetDirection.as_view(), name='direction'),
    path('api/land/', views.Land.as_view(), name='land'),
    path('api/rtl/', views.ReturnToLaunch.as_view(), name='rtl'),
    path('api/command/<int:pk>/', views.LatestCommand.as_view(), name='command'),
    path('api/list/', views.AgentList.as_view(), name='agent_list'),
    path('delete_agents/', views.delete_agents, name='delete_agents'),
    path('set_agents/', views.set_agents, name='set_agents'),
    path('get_agents_names/', views.get_agents_names, name='get_agents_names'),
    re_path(r'^agent/', views.agents, name='agents'),
    re_path(r'^ui/direction/', views.set_direction, name='set_direction'),
    re_path(r'^', views.users, name='users'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

agent/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

DictCommand = ['None', 'Takeoff', 'Land', 'GoHome', 'SetDirection']


class MainAxis(models.Model):
    main_axis = models.IntegerField(default=0)


class AgentFov(models.Model):
    agent_fov = models.CharField(max_length=200)


class TimeStampValidityPeriod(models.Model):
    time_stamp_validity_period = models.FloatField(default=0)


class Agent(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    rotation_x = models.FloatField(default=0)
    rotation_y = models.FloatField(default=0)
    rotation_z = models.FloatField(default=0)
    rotation_w = models.FloatField(default=0)
    translation_x = models.FloatField(default=0)
    translation_y = models.FloatField(default=0)
    translation_z = models.FloatField(default=0)
    time_stamp = models.DateTimeField(default=0)
    parent = models.CharField(max_length=200)
    # from prev agent
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    altitude = models.FloatField(default=0)
    azimuth = models.FloatField(default=0)
    armed = models.BooleanField(default=False)
    bat_volt = models.FloatField(default=0)
    gps_fix = models.IntegerField(default=0)
    gps_hdop = models.FloatField(default=0)
    mode = models.CharField(max_length=20)
    llc_message = models.CharField(max_length=200)
    llc_state = models.CharField(max_length=20)
    hlc_state = models.CharField(max_length=20)
    mc_state = models.CharField(max_length=20)

    def __str__(self):
        return "Agent " + str(self.name)


class AgentUidName(models.Model):
    uid = models.IntegerField(default=0, primary_key=True)
    name = models.CharField(max_length=200)


class Operator(models.Model):
    command = models.IntegerField()
    direction = models.FloatField('Azimuth in degrees')
    server_timestamp = models.DateTimeField('server reception time')

    def __str__(self):
        return DictCommand[self.command]

    def NoCommand(self):
        self.command = 0
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()

    def Takeoff(self):
        self.command = 1
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()

    def Land(self):
        self.command = 2
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()

    def RTL(self):
        self.command = 3
        self.direction = -1
        self.server_timestamp = timezone.now()
        self.save()

    def SetDirection(self, direction):
        self.command = 4
        self.direction = direction
        self.server_timestamp = timezone.now()
        self.save()

    def isRelevant(self):
        timedeltaFromLastCommand = timezone.now() - self.server_timestamp
        return ((timedeltaFromLastCommand.seconds < 3) and (0 <= timedeltaFromLastCommand.seconds))

agent/views.py
import pytz
from django.urls import reverse
from .models import Agent, AgentUidName, Operator, TimeStampValidityPeriod, AgentFov, MainAxis
import json


from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from scipy.spatial.transform import Rotation as R
import numpy as np
import math
from agent.serializers import AgentSerializer, OperatorSerializer

utc = pytz.UTC
agent_pov_cos = -1
main_axis = 'W'
axis = {'X': 0, 'Y': 1, 'Z': 2}

# ---------------------------------- Helper functions ---------------------------------


def get_latest_operator():
    if not Operator.objects.exists():
        user = Operator()
        user.NoCommand()
    else:
        user = Operator.objects.order_by('-server_timestamp')[0]
    return user


def detect_other_agents(agent):
    if not valide_time_stamp(agent):
        return False
    for other in Agent.objects.exclude(name=agent.name):
        if not valide_time_stamp(other):
            continue
        if not validate_same_parent(agent, other):
            continue
        cos_angle = calc_cos(agent, other)
        if agent_pov_cos <= cos_angle <= 1:
            return True
    return False


def valide_time_stamp(agent):
    time_stamp_validity_period = TimeStampValidityPeriod.objects.values_list('time_stamp_validity_period', flat=True)[0]
    time_stamp_validity_period = datetime.timedelta(seconds=time_stamp_validity_period)
    if datetime.datetime.now().replace(tzinfo=utc) > agent.time_stamp + time_stamp_validity_period:
        agent.delete()
        return False
    return True


def calc_cos(agent, other):
    # """
    # Finds the vec from agent to other in the labs' axis, transform it to the agents' axis,
    # and calculates the cos between this vector and the main axis of the agent
    # """
    set_agent_pov_cos()
    set_main_axis()
    vec_agent_other = np.array(
        [other.translation_x - agent.translation_x, other.translation_y - agent.translation_y,
         other.translation_z - agent.translation_z])
    trans_agent = R.from_quat(
        [-agent.rotation_x, -agent.rotation_y, -agent.rotation_z, agent.rotation_w])
    vec_other_in_agent = trans_agent.apply(vec_agent_other)
    return vec_other_in_agent[axis[main_axis]] / (
        np.sqrt(vec_other_in_agent[axis['X']] ** 2 + vec_other_in_agent[axis['Y']] ** 2 + vec_other_in_agent[
            axis['Z']] ** 2))


def set_agent_pov_cos():
    global agent_pov_cos
    if agent_pov_cos == -1:
        agent_pov = AgentFov.objects.values_list('agent_fov', flat=True)[0]
        agent_pov_cos = np.cos(math.radians(agent_pov / 2))


def set_main_axis():
    global main_axis
    if main_axis == 'W':
        main_axis = MainAxis.objects.values_list('main_axis', flat=True)[0]


def validate_same_parent(agent, other):
    if agent.parent != other.parent:
        return False
    return True


# --------------------------------- API ----------------------------------

class API(APIView):

    def get(self, request, format=None):
        reply = {
            'Takeoff': reverse('agents:takeoff', request=request, format=format),
            'Set Direction': reverse('agents:direction', request=request, format=format),
            'Land': reverse('agents:land', request=request, format=format),
            'Return to Launch': reverse('agents:rtl', request=request, format=format),
            'Last Operator Command': reverse('agents:command', args=('1',), request=request, format=format),
            'Agent List': reverse('agents:agent_list', request=request, format=format)
        }
        return Response(reply)


class LatestCommand(generics.RetrieveAPIView):
    """
    Latest Command Input
    """
    queryset = Operator.objects.all()
    serializer_class = OperatorSerializer


class AgentList(generics.ListAPIView):
    """
    A list of current active agents
    """
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer


class Takeoff(APIView):
    """
    Operator Command to all listening agents to perform a takeoff
    """

    def post(self, request, format=None):
        user = get_latest_operator()
        user.Takeoff()
        return Response(status=200)


class SetDirection(APIView):
    """
    Operator Command to all listening agents to move towards some direction \
    (direction x in degrees, 0 <= x < 360) for 3 seconds.\
    Example : {"direction": 64}
    """

    def post(self, request, format=None):
        reply = Response(status=200)
        direction = 0
        try:
            direction = float(request.data['direction'])
        except Exception as e:
            reply = Response(data=e.__str__(), status=400)
        else:
            if ((0 <= direction) and (360 > direction)):
                user = get_latest_operator()
                user.SetDirection(direction)
            else:
                reply = Response(data='Azimuth out of bounds.', status=400)
        return reply


class Land(APIView):
    """
    Operator Command to all listening agents to land
    """

    def post(self, request, format=None):
        user = get_latest_operator()
        user.Land()
        return Response(status=200)


class ReturnToLaunch(APIView):
    """
    Operator Command to all listening agents to return to launch
    """

    def post(self, request, format=None):
        user = get_latest_operator()
        user.RTL()
        return Response(status=200)


# --------------------------------------------- UI -------------------------------------------

def users(request):
    return render(request, 'operator.html')


def set_direction(request):
    """
    Similar to update, just accepts a POST with a direction command.
    """
    reply = HttpResponse(status=405)
    if 'POST' == request.method:
        user = get_latest_operator()
        user.SetDirection(request.POST['direction'])
        reply = HttpResponse(status=405)
    return reply


# --------------------------------------- Agent -----------------------------------------------


@api_view(['POST'])
def agents(request):
    # """
    # Responds to an agent's POST request with the latest Operator's command.
    # """
    reply = HttpResponse(content='POST expected', status=405)
    if 'POST' == request.method:
        dict_message = json.loads(request.POST['root'])

        agent_uid = int(dict_message['Message']['Header']['Topic'])
        print(agent_uid)
        detected = False

        # Check if other agents are in this agent's field of view
        try:
            agent_uid_name = AgentUidName.objects.get(uid=agent_uid)
            agent_name = agent_uid_name.name
            agent = Agent.objects.get(name=agent_name)
        except:
            print("Agent does not exist")
        else:
            agent.latitude = float(dict_message['Message']['Body']['Lat']),
            agent.longitude = float(dict_message['Message']['Body']['Lon']),
            agent.altitude = float(dict_message['Message']['Body']['Alt']),
            agent.azimuth = float(dict_message['Message']['Body']['Yaw']),
            agent.armed = (1 == int(dict_message['Message']['Body']['Armed'])),
            agent.bat_volt = float(dict_message['Message']['Body']['Volt']),
            agent.gps_fix = int(dict_message['Message']['Body']['GpsFix']),
            agent.gps_hdop = float(dict_message['Message']['Body']['GpsHdop']),
            agent.mode = dict_message['Message']['Body']['Mode'],
            agent.llc_message = dict_message['Message']['Body']['LlcMessage'],
            agent.llc_state = dict_message['Message']['Body']['LlcState'],
            agent.hlc_state = dict_message['Message']['Body']['HlcState'],
            agent.mc_state = dict_message['Message']['Body']['McState']
            detected = detect_other_agents(agent)

        user = get_latest_operator()

        if not user.isRelevant():
            user.NoCommand()

        reply = {
            'id': agent_uid,
            'command': user.command,
            'direction': user.direction,
            'payload':
                {
                    'detected': detected
                },
            'timestamp': user.server_timestamp.__str__()
        }
        reply = HttpResponse(json.dumps(reply))
    return reply


# ---------------------------------- MocapProxy ---------------------------------


@api_view(['POST'])
def delete_agents(request):
    if 'POST' == request.method:
        Agent.objects.all().delete()
        return HttpResponseRedirect(reverse('agents:users'))
    else:
        return HttpResponse(content='POST expected')


@api_view(['POST'])
def get_agents_names(request):
    if 'POST' == request.method:
        agents_query = AgentUidName.objects.all().values()
        agents_names = []
        for agent in agents_query:
            agents_names.append(agent)
        return HttpResponse(json.dumps(agents_names, default=str))
    else:
        return HttpResponse(content='POST expected')


@api_view(['POST'])
def set_agents(request):
    if 'POST' == request.method:
        start = datetime.datetime.now()
        request = json.load(request)
        num_agents = len(request)
        for index in range(num_agents):
            agent = request[str(index)]
            name = agent['name']
            rotation_x = agent['rotation_x']
            rotation_y = agent['rotation_y']
            rotation_z = agent['rotation_z']
            rotation_w = agent['rotation_w']
            translation_x = agent['translation_x']
            translation_y = agent['translation_y']
            translation_z = agent['translation_z']
            time_stamp = datetime.datetime.now().replace(tzinfo=utc)
            parent = agent['parent']
            if Agent.objects.filter(name=name).exists():

agent/templates/api.html
{% extends "rest_framework/base.html" %}

{% block branding %}
    <a class="navbar-brand" rel="nofollow" href="https://gitlab.com/nemala/operator-station">
		NeMALA / Operator Station API 
    </a>
{% endblock %}

{% block title %}
   {{ name }} - NeMALA / API
{% endblock %}

agent/templates/operator.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>IndoorOperatorStation</title>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Optional meta tags -->
    <meta name="description" content="An Operator Station for Swarming Agents">
    <meta name="author" content="Ron">
    
    <!-- Distribution Includes -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="http://yui.yahooapis.com/3.18.1/build/yui/yui-min.js"></script>

    <!-- Static Custom Look & Feel -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'agent/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'agent/grid.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'agent/direction_control.css' %}" />
	<link rel="shortcut icon" href="{% static 'agent/favicon.ico' %}" />
    <script src="{% static 'agent/knob_customization.js' %}"></script>
    <script src="{% static 'agent/main.js' %}"></script>
    
	<!-- On document load, ready all JS functionality -->
	<script>
	$(document).ready(function()
	{


		$("#status").hide()
	    $("#status").click(function(event)
	   	{
	    	event.preventDefault();
	    	if (document.getElementById("directionCheck").checked)
	    	{
	    		$.post("{% url 'agent:set_direction' %}", 
	    		{
	    			direction: $("#direction_value").val(),
	    			csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
	    		},
	    		function(response)
	    		{
	    			UpdateStatus(response);
	    		});	 
	    	}
	    });
		
		$("#takeoff").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:takeoff' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });
		
		$("#land").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:land' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });
		
		$("#RTL").click(function(event)
	   	{
	    	event.preventDefault();
    		$.post("{% url 'agent:rtl' %}",
				{
					csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
				}
			);
	    });


	});
	</script>
  </head>
  
  <body>
  	<div class="grid-container" id="main_container">
  		<div class="header">
  			<h2>Control the Swarm Indoors</h2>
  		</div>
		<div class="middle" id="Action" style="background-color:#ccc;">
			<h2>Actions</h2>
			<form action="{% url 'agent:takeoff' %}" method="post"  id="takeoff">
				{% csrf_token %}<input class="full_width" type="submit" value="Take off!">
			</form>

			<div class="direction_control">
				<div class="direction_control_toggle">
					<label class="switch">
						<input type="checkbox" id="directionCheck"/>
						<span class="slider"></span>
					</label>
				</div>
				<div class="direction_control_dial">
					<div  class="yui3-skin-sam"> <!-- You need this skin class -->
						<div id="direction_knob"></div>
					</div>
				</div>
				<input id="direction_value" type="text" value=""/>
			</div>
			
			<form action="{% url 'agent:land' %}" method="post" id="land">
				{% csrf_token %}<input class="full_width" type="submit" value="Land">
			</form>
				
			<form action="{% url 'agent:rtl' %}" method="post" id="RTL">
				{% csrf_token %}<input class="full_width" type="submit" value="Return To Launch">
			</form>


	  	</div><!-- Action -->
	  	<div class="footer">
	  		<p>© 2022 Ron Tcherner - MIT License</p>
	  	</div>
	</div><!-- main_container -->
  </body>
  
</html>